worker_processes 1;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    default_type text/html;

    client_body_temp_path /tmp/client_body;
    proxy_temp_path /tmp/proxy;
    fastcgi_temp_path /tmp/fastcgi;

    server {
        listen 81;

        location / {
            fastcgi_pass 127.0.0.1:8080;
        }

        location = /status {
            stub_status;
            access_log off;
        }
    }
}
