worker_processes 1;

events {
    worker_connections 1024;
}

http {
    default_type text/html;

    server {
        listen 81;

        location / {
            fastcgi_pass 127.0.0.1:8080;
        }

        location = /status {
            stub_status;
            access_log off;
        }
    }
}
